### ISSUE TITLE
tcl interpreter source is too big

### ISSUE THREAD

**Issue by rofl0r** [msteveb/autosetup#15]
assuming the jim0.c in this git repo is the one shipped with autosetup'd packages, 560KB is added to every single shipped package. this is by far more bloated than typical (sane) autoconf stuff.
ideally the interpreter should be much leaner (it takes 45 secs to compile on my 800 mhz arm netbook): but as a first step it could notably reduced in filesize for shipping by applying some source code transformations.

``` perl
while(<>) {
    my @a = split /\s+/;
    next if !defined($a[0]);
    for my $i(0..scalar(@a)-2) {
        print $a[$i] . " " if length($a[$i]);
    }
    print $a[scalar(@a)-1], "\n";
}
```

applying this script to remove adjacent whitespace reduces the filesize by 130 kb already.
further improvements could be achieved by using short defines like U for often used words like interp etc  and by removing unnecessary spacing (for example between ) and {).
also there seems to be code like tcp/ip stuff that could be stripped away for distribution.
optimally the interpreter source is <100kb and compiles in less than 10 sec on slow devices in the end.

**Comment by msteveb** [comment]
I'm not sure that anything much can be done about this other than not supplying jimsh0.c as a fallback and requiring either jimsh or tclsh to be installed. If you compare a similar language, lua, it is also about 20k lines of code (compared to 22k for jimsh0.c), so it is much of a muchness.
Closing this ticket.
