### ISSUE TITLE
@top_srcdir@ not absolute beside the documentation

### ISSUE THREAD

**Issue by bapt** [msteveb/autosetup#16]
I use @top_srcdir@ in compat/Makefile.in like this SRCDIR= @top_srcdir@/something and I end up with ./something instead of an absolute path (note that . is not even correct, it should be .. for relative)

**Comment by msteveb** [comment]
Thanks for the report. Are you able to create a comparative test case with autoconf? I don't see any suggestion that top_srcdir is supposed to be absolute, so in this regard autosetup is misleading.

There seems to be abs_top_srcdir. Should autosetup add support for this variable?

**Comment by msteveb** [comment]
BTW. Why do you want to use @top_srcdir@ rather than @srcdir@? make-template carefully arranges for @srcdir@ to be the relative path to the top of the source, which is normally what you want.

**Comment by bapt** [comment]
It does not
here is my test:

compat/Makefile.in:
s = @srcdir@
ts = @top_srcdir@

With autosetup the generated Makefile is:
s = .
ts = .

with autoconf, the generated Makefile is:
s = .
ts = ..

Note that is works for both as I expect when build outsource
mkdir /tmp/build
~/test/configure
cat compat/Makefile

With autoconf:
s = /home/bapt/test/compat
ts = /home/bapt/test

with autosetup
s = /home/bapt/test/compat
ts = /home/bapt/test

Also works when outdir is inside the sourcedir
mkdir build
../configure

with autoconf:
cat compat/Makefile
s = ../compat
ts = ..

with autosetup
cat compat/Makefile
s = ../compat
ts = ..

**Comment by msteveb** [comment]
Can you try this fix and let me know if you agree it is correct?

https://gist.github.com/msteveb/ff4830198312181a8e2c

**Comment by bapt** [comment]
tested with success, thank you !
