### ISSUE TITLE
website: broken links

### ISSUE THREAD

**Issue by frgm** [msteveb/autosetup#17]
https://msteveb.github.io/autosetup/ :
    Jim Tcl => http://jim.berlios.de/

http://msteveb.github.io/autosetup/developer/examples/ :
    redis => http://redis.io/ - new homepage
   Jim Tcl Project => http://jim.berlios.de/ 

https://msteveb.github.io/autosetup/developer/ : 
    waf => https://waf.io/ - new homepage
    Tcl Scripting => 404
    Modules => 404

https://msteveb.github.io/autosetup/why/ : 
    http://jim.berlios.de/

**Comment by msteveb** [comment]
Thanks for the report. I think I fixed them all, except the missing pages are a bit sparse.
