### ISSUE TITLE
website: typos

### ISSUE THREAD

**Issue by frgm** [msteveb/autosetup#20]
"If the doesn’t exist" : [developer/reference](https://github.com/msteveb/autosetup/blob/707a6676979a006c194946f7fdeeee99a56173fb/developer/reference/index.html#L132)
"idiosyncracies In general" : [developer/reference](https://github.com/msteveb/autosetup/blob/707a6676979a006c194946f7fdeeee99a56173fb/developer/reference/index.html#L198)
"to strip to strip" : [developer/reference](https://github.com/msteveb/autosetup/blob/707a6676979a006c194946f7fdeeee99a56173fb/developer/reference/index.html#L246)
"decl" : [developer/reference](https://github.com/msteveb/autosetup/blob/707a6676979a006c194946f7fdeeee99a56173fb/developer/reference/index.html#L295)
"given given" : [developer/reference](https://github.com/msteveb/autosetup/blob/707a6676979a006c194946f7fdeeee99a56173fb/developer/reference/index.html#L307)
"It the executable is not found" : [developer/reference](https://github.com/msteveb/autosetup/blob/707a6676979a006c194946f7fdeeee99a56173fb/developer/reference/index.html#L331)

"@ CC@ is replace" : [developer](https://github.com/msteveb/autosetup/blob/96fb39e6f091775650642bf531313b69536699ca/developer/index.html#L307)

**Comment by msteveb** [comment]
Fixed. Thanks.
