### ISSUE TITLE
website: typos

### ISSUE THREAD

**Issue by frgm** [msteveb/autosetup#21]
last time I've read the docs not very careful..

"need to selected" : [user](https://github.com/msteveb/autosetup/blob/707a6676979a006c194946f7fdeeee99a56173fb/user/index.html#L116) => missing 'be' ?
"as the default if is not provided" : [developer/reference](https://github.com/msteveb/autosetup/blob/32353f943a9d555ae3a1d8fac7e01aa7830e4440/developer/reference/index.html#L91) => missing 'it' ?
"idiosyncracies" : [developer/reference](https://github.com/msteveb/autosetup/blob/32353f943a9d555ae3a1d8fac7e01aa7830e4440/developer/reference/index.html#L198) => idiosyncrasies
"the the" : [developer/reference](https://github.com/msteveb/autosetup/blob/32353f943a9d555ae3a1d8fac7e01aa7830e4440/developer/reference/index.html#L444)
"EXEXT" : [developer/reference](https://github.com/msteveb/autosetup/blob/32353f943a9d555ae3a1d8fac7e01aa7830e4440/developer/reference/index.html#L418) => EXEEXT

“=&gt; description : [developer/reference](https://github.com/msteveb/autosetup/blob/32353f943a9d555ae3a1d8fac7e01aa7830e4440/developer/reference/index.html#L93) -> missing "

**Comment by msteveb** [comment]
Fixed. Thanks!
