### ISSUE TITLE
configure --help prints hard-coded value for default prefix despite defaultprefix

### ISSUE THREAD

**Issue by tangentsoft** [msteveb/autosetup#22]
If you say something like

    define defaultprefix /opt/mypackage

before the `system` module gets included, that overrides the default of `/usr/local` for the `configure --prefix` option, but `./configure --help` still claims `--prefix` defaults to `/usr/local` because it has that value hard-coded into its message text. It needs to use the `defaultprefix` value here instead.

I'd make the change myself, but my Tcl is waaaay rusty. :)

I *can* tell you that the change needs to be somewhere around line 28 in `autosetup/system.tcl`.

**Comment by msteveb** [comment]
Thanks for the report. I'll see what I can do

**Comment by msteveb** [comment]
Fixed in git. Please try it out.

**Comment by tangentsoft** [comment]
Thank you!

I actually attempted very much the same thing, but got stuck on Tcl's baroque quoting rules.

Your change is applied to [my repository](https://tangentsoft.com/pidp8i/wiki?name=Home), which you may be interested to see, if only to know that other people are happily using your configuration system. Pretty pics [here](https://tangentsoft.com/pidp8i/wiki?name=Warren%27s+PiDP-8/I+System).

**Comment by msteveb** [comment]
Cool! Good to see it's getting some use. If you think Tcl's quoting is baroque, try looking at an autoconf-generated configure script. Surely anyone can read stuff like this:

```
as_me=`$as_basename -- "$0" ||
$as_expr X/"$0" : '.*/\([^/][^/]*\)/*$' \| \
     X"$0" : 'X\(//\)$' \| \
     X"$0" : 'X\(/\)' \| . 2>/dev/null ||
$as_echo X/"$0" |
    sed '/^.*\/\([^/][^/]*\)\/*$/{
        s//\1/
        q
      }
      /^X\/\(\/\/\)$/{
        s//\1/
        q
      }
      /^X\/\(\/\).*/{
        s//\1/
        q
      }
      s/.*/./; q'`
```
