### ISSUE TITLE
--xxxdir= options no longer like $'s

### ISSUE THREAD

**Issue by aryler** [msteveb/autosetup#23]
This used to work:
--docdir='${prefix}/share/doc/jim'
Now, @docdir@ will be messed-up in the Makefile.

I don't know if this now how things should be, and the change wasn't more than a minor irritation for me, so I'm not sure if this is a bug report or just complaining.  :)

**Comment by msteveb** [comment]
It's not just complaining, this is a legitimate bug! But did you mean to report this against msteveb/jimtcl? Fixed there. Thanks!

**Comment by aryler** [comment]
I was going to report in jimtcl but I thought here would be the right place. No problemo, I'll stick to the jimtcl repo from now on. Thanks.
