### ISSUE TITLE
Allow setting of options from within auto.def

### ISSUE THREAD

**Issue by gahr** [msteveb/autosetup#27]
To handle dependencies among options, it would be nice to be able to force the value of an option from within auto.def.

```tcl
if {[opt-bool depends-on-foo]} {
   set-opt-bool foo ;# this here
}
```

Maybe there's a way to do that already and I just missed it. Thought?

**Comment by gahr** [comment]
I currently have this workaround, but I guess that dict is not supposed to be directly modified outside of the autosetup module:
```tcl
dict set ::autosetup(optset) foo 1
```

**Comment by msteveb** [comment]
Don't be afraid use defines or Tcl variables to capture the options. e.g.

````
define USE_BLAH [opt-bool blah]
if {[opt-bool foo]} {
  # foo always selects blah
  define USE_BLAH
  define USE_FOO
}
````

Definitely don't set autosetup(optset) directly since the internal details can change.

**Comment by gahr** [comment]
Ah good idea, like this I can concentrate the capture of setting of a number of options in the top lines and never user [opt-*] below the block.

```tcl
define USE_BAZ [opt-bool baz]
define USE_FOO [opt-bool foo]

# many lines of code
if {[is-defined USE_FOO]} {
  define USE_BAZ
  # things for foo
}

# many lines of code
if {[is-defined USE_BAZ]} {
  # either by the user or by foo
}
```
