### ISSUE TITLE
Add @abs_top_srcdir@

### ISSUE THREAD

**Issue by tangentsoft** [msteveb/autosetup#29]
I just ran into a bit of a buzz saw trying to use `@top_srcdir@` in a project.

The situation is that I have a script `tools/foo.in` which needs to refer to files stored elsewhere in the source tree. The script is called as `tools/foo` from the top-level Makefile, so CWD is `tools/..`, which means you cannot simply prepend `@top_srcdir@` to source tree paths in the obvious way:

    media_path = "@top_srcdir@/media"

because it turns into `../media`, which when interpreted from the CWD of the script tries to look for a `../media` directory relative to the top-level source directory, where `make` is run from. There is no such directory, so it fails.

`@srcdir@` doesn't help here: it only shifts the same problem by one directory level.

Building out-of-tree adds a second layer to the problem since these autosetup variables become absolute paths, so the above example turns into `/path/to/source/tree/media`, so it's now pointing at the directory we intended above: that is, `../media` relative to the `tools` directory, rather than relative to the top source directory! This means you cannot fix the problem so it works with both cases, due to this mix of absolute and relative paths.

The solution is this one-liner in `auto.def`:

     define abs_top_srcdir [file normalize [get-define top_srcdir]]

This does two things:

1. By doing it in `auto.def`, the definition of `@top_srcdir@` doesn't depend on CWD being equal to the current file's location. CWD is the top of the source tree at this point, by definition.

2. By normalizing the path, we don't have a behavior shift between building in-tree and building out-of-tree. The path refers to the same directory in both cases: the top source directory, as it says on the label.

I realize you can't just redefine the way `@srcdir@` and `@top_srcdir@` are defined, since other projects will have made their separate accommodations with its current definition, and thus may break if you "fix" their definitions. 

I am instead asking that you add the above definition or something like it as an alternative to `@top_srcdir@`.

**Comment by msteveb** [comment]
Thanks for the suggestion. We can't change srcdir or top_srcdir because they need to be autoconf-compatible. I'm fine with adding abs_top_srcdir too since it is available in autoconf.

BTW, I try to avoid using template replacement for this sort of case. Instead, consider using $(dirname $0) in the script and find things relative to the location of the script, or set a makefile variable such as TOPDIR that can be used in the script to find the top dir.

Anyway, I'll add abs_top_srcdir
