### ISSUE TITLE
lpop needs use util

### ISSUE THREAD

**Issue by gahr** [msteveb/autosetup#36]
The `lpop` proc introduced in 92515acf98 needs `use util` to be visible from `make-template`. I think this should be transparent from the user's point of view.

In testbed, this is mitigated by the call to `autosetup-require-version`, which itself calls `use util`. Is it assumed that a call to `autosetup-require-version` be there for the whole machinery to work, or would it be better to explicitely `use util` in autosetup?

Also, small typo in `compatiblity` [here](https://github.com/msteveb/autosetup/blob/master/autosetup#L467) - I'm not opening a separate PR for that ;)

Thanks!

**Comment by msteveb** [comment]
Thanks. I missed that. I pushed a fix to always use util since it is useful enough
