### ISSUE TITLE
[Typo] Should be cc-shared not cc-chared

### ISSUE THREAD

**Issue by seishinryohosha** [msteveb/autosetup#39]
https://github.com/msteveb/autosetup/blob/01c0e9241eaa4c938489dd83197b258f08d8c9fb/examples/typical/auto.def#L4

In https://github.com/msteveb/autosetup/commit/fc665b9c98d6348a49cedb26188e3bce9e32ac4b an typo occurred, so now the example doesn't work.

`cc-chared` should be `cc-shared`

**Comment by msteveb** [comment]
Fixed. Thanks!
