### ISSUE TITLE
cc-check-flag "mismatch": cc-check-flag says yes, but the compiler says no

### ISSUE THREAD

**Issue by sgbeal** [msteveb/autosetup#40]
This isn't really a bug, per se, but is an unfortunate side-effect of how cc-check-xxx works:

```
$ CC_FOR_BUILD=clang CC=clang ./configure
...
Checking whether the C compiler accepts -Wimplicit-fallthrough=5...yes
...

$ make
...
+ clang ... test.c
warning: unknown warning option '-Wimplicit-fallthrough=5'; did you mean '-Wimplicit-fallthrough'? [-Wunknown-warning-option]
```

That "mismatch" would seem to be a side-effect of cc-check-xxx necessarily compiling with no warning/error flags. 

There is a workaround, and i'm posting this ticket primarily to document that workaround in case anyone else stumbles over this (not because i expect that this can be fixed in autosetup):

```
cc-with {-cflags {-Wall -Wextra -Werror}} {
    cc-check-flags -Wimplicit-fallthrough=5
}
```

That (as hoped) will pass on gcc7+ but fail on clang.

(And, for the public record, i _HATE_ the gcc devs for making implicit fall-through a warning offense. One does not simply take a perfectly valid, widely-used 40-year-old feature and suddenly start reporting it via the warning flags. Those of us who habitually compile with `-Werror` now all hate you guys. We all now get to go "fix" all of our well-behaved source trees to please that handful of people who can't handle switch fall-through properly. Grrrrr.)

**Comment by msteveb** [comment]
Probably just need:

```
cc-with {-cflags -Werror} {
  cc-check-flags -Wimplicit-fallthrough=5
}

```

Should cc-check-flags always use -Werror? Really only when checking for a warning flag, since an unknown warning is just a warning, not an error.

**Comment by sgbeal** [comment]
Closing - this ticket was really just for documentation purposes. autosetup, IMO, does the most sensible thing here, it's just surprising/unexpected when first encountered.
