### ISSUE TITLE
AUTOREMAKE does not honor CC [from the environment]

### ISSUE THREAD

**Issue by sgbeal** [msteveb/autosetup#41]
If CC is specified to a non-default compiler when running `./configure`, that same CC is not used when auto-reconfigure kicks in. To get this effect, the `auto.def` needs something like:

```
    set cc [opt-val cc]
    if {[string length $cc]} {
        define CC $cc
        define CC_FOR_BUILD $cc
    }
```
my recommendation would be to either include CC=xxx to the AUTOREMAKE command or to add a set of common flags (to the cc module) which do something like the above for CC and CC_FOR_BUILD (which my example doesn't handle properly because it's presumably for cross-compiling, which i never do).

**Comment by sgbeal** [comment]
Update: it seems that CC is honored and propagated if CC=blah passed as an argument to `configure`, rather than coming in from the environment.

So:
```
./configure CC=clang CXX=clang
```

propagates CC and CXX through AUTOREMAKE, but this does not:

```
CC=clang CXX=clang ./configure
```

That's arguably a bug... and arguably not. Either way, the docs should probably point out that difference.

**Comment by msteveb** [comment]
I agree that it's a bug. I've pushed a fix.
