### ISSUE TITLE
AUTOREMAKE misbehaviour with subdirs

### ISSUE THREAD

**Issue by sgbeal** [msteveb/autosetup#42]
When AUTOREMAKE is triggered by a subdirectory's makefile, paths resolved in the `auto.def` are treated as relative to the current (sub) dir. This causes, e.g., `configure` to write generated files in the subdir instead of the top dir. My recommendation is to add a `cd $builddir &&` or `cd $builddir;` to the start of AUTOREMAKE, like i've done in my `Makefile.in`:

```
AUTOREMAKE := cd @TOP_SRCDIR@; @AUTOREMAKE@
```

**Comment by msteveb** [comment]
I put an explanation in examples/testbed/subdir/Makefile.in, but it might be hard to discover. Where should this go in the documentation to make it easy to find?
