### ISSUE TITLE
Building in a path containing spaces

### ISSUE THREAD

**Issue by paulfertser** [msteveb/autosetup#43]
When trying to build an autoconf-based OpenOCD its `configure` calls `configure.gnu` in `jimtcl/` which in turn `exec`s autosetup's `configure.` This results in `$0` (and hence `dir` variable) containing full path and so it needs to be quoted inside the backticks for `autosetup-find-tclsh` invocation.

**Comment by msteveb** [comment]
Thanks for the feedback. The use of $0 is quoted:

  d=`dirname "$0"`

Is OpenOCD using an old version?

**Comment by paulfertser** [comment]
OpenOCD is using https://github.com/msteveb/jimtcl/blob/0.77/autosetup/autosetup#L1486 which I assume is essentially the same as https://github.com/msteveb/autosetup/blob/master/lib/install.tcl#L168 . And `$dir` is not quoted _inside the backticks_.

**Comment by msteveb** [comment]
Got it. I've pushed a fix.
