### ISSUE TITLE
clang: config tests for C++ need to use .cpp extension instead of .c

### ISSUE THREAD

**Issue by sgbeal** [msteveb/autosetup#44]
After a system update which includes clang 6.0, my configure scripts stopped including -fPIC in my C++ code, which leads to building of shared libraries to fail with a "recompile with -fPIC" message. The culprit is:

```
============
Failed: c++ -g -O2 -c -Werror -Wall -Wextra -Wsign-compare -fPIC -Werror conftest__.c -o conftest__.o
clang: error: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Werror,-Wdeprecated]
============
The failed code was:
int main(void) {

return 0;
}
```

The corresponding `auto.def` test is:

```
cc-with {-lang c++} {
    cc-check-flags -fPIC
}
```
The `-Werror` and friends flags which appear in the logs are injected by a prior `auto.def` test:

`cc-check-flags -Werror -Wall -Wextra -Wsign-compare -fPIC`

i've been able to work around this by moving that second test below the C++ -fPIC test, but that is somewhat unsatisfying because i want the C++ compiler to pedantically fail if it doesn't understand `-fPIC` and it _might_ not if `-Werror` is missing (it might just warn about the unsupported flag, but still exit with rc 0).

In any case, when compiling a test snippet in C++ mode, the temp file name should probably have a `.cpp` or `.c++` extension rather than `.c`, since clang complains about that extension assumption. Alternately, perhaps a completely arbitrary extension, like `.xxx`, might stop it from complaining.

**Comment by msteveb** [comment]
This seems reasonable. autoconf explicitly uses .cpp when compiling C++. We can do the same. I'll push a fix.

**Comment by msteveb** [comment]
Please try current git

**Comment by sgbeal** [comment]
Works for me :). Thank you!

```
============
Compiled OK: c++ -g -O2 -c -Werror -Wall -Wextra -Wsign-compare -fPIC conftest__.cpp -o conftest__.o
============
int main(void) {

return 0;
}
```
