### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by tangentsoft** [msteveb/autosetup#46]
Checkin [92515acf9] introduces an incompatibility in the script file syntax that's still documented the old way on the github.io site.

The project could use a ChangeLog.md file to call out such things as well. I had to go digging through the checkin stream to figure out what happened here on upgrading from 0.6.7.

**Comment by msteveb** [comment]
Thanks. The static website generator I use has undergone a major revision, so it will take some time before I can update the github.io site

**Comment by msteveb** [comment]
I've updated the website generator now and updated the command reference
