### ISSUE TITLE
Regex for @if/@else/@endif processing needs tightening

### ISSUE THREAD

**Issue by tangentsoft** [msteveb/autosetup#48]
This regex in `lib/system.tcl` is too loose: `^@(if|else|endif)\s*(.*)`

1. It allows zero spaces between `@if` and the variable name; it should require at least 1
2. It allows junk after `@else` and `@endif`

I suggest changing it to `^@(if\s+(.*)|else|endif)$`, assuming Tcl's regex engine allows nested grouping and the inner one continues to get treated as "second" as it currently is. If Tcl regexes can't cope with that, then you'll have to keep the `(.*)` bit at the end of the RE and handle the second problem separately, such as by checking for empty `condargs` in the `else` and `endif` cases.

If you do this, it should be changed after merging my recent PR, if you're going to accept it, because it moves the affected line, which would create a merge conflict if you change it before merging the PR.

**Comment by msteveb** [comment]
Try current git
