### ISSUE TITLE
Find function in nonstandard library feature

### ISSUE THREAD

**Issue by tangentsoft** [msteveb/autosetup#52]
Autosetup should have a way to say "find a function `foo()` defined in `foo.h` and provided in `libfoo` underneath canonically-structured directory `/foo`". Autosetup provides all of the pieces to do this, but not a single wrapper function for it all.

I believe this should be a core function because it's a common pattern to have a non-system directory with `lib` and `include` subdirs which provide and declare (respectively) a non-standard library interface that a program needs to run. If found, you should have the option to modify `CFLAGS`, `LDFLAGS`, and `LIBS` accordingly or to define a separate set of parallel variables with the necessary flags.

The specific need that sparked this is linking a program to `bcm_host.so` on a Raspberry Pi, with functions defined in `bcm_host.h`, both under non-system directory `/opt/vc`. This is a common pattern, used by many other non-system libraries.

I just wrote the following bit in an `auto.def` file, but it seems like something like it should be provided by Autosetup so I can make a one-line call to it from my `auto.def` file.

```tcl
# Check for libraspberrypi-dev stuff
set old_LIBS [get-define LIBS]      ;# don't want LIBS modded directly
if {![file isdirectory "/opt/vc"]} {
    msg-result "WARNING: Not building on a Pi or libraspberrypi-dev not installed!"
    define PI_CFLAGS ""
    define PI_LFLAGS ""
    define PI_LIBS   ""
} elseif {![cc-with {-cflags "-L/opt/vc/lib"} {
             cc-check-function-in-lib bcm_host_get_peripheral_address bcm_host
           }]} {
    user-error "Found /opt/vc but cannot link to -lbcm_host!"
} elseif {![cc-with {-cflags "-I/opt/vc/include"} {
             cc-check-includes bcm_host.h
           }]} {
    user-error "Found /opt/vc but cannot #include bcm_host.h!"
} else {
    define PI_CFLAGS "-I/opt/vc/include"
    define PI_LFLAGS "-L/opt/vc/lib"
    define PI_LIBS   "-lbcm_host"
}
define LIBS $old_LIBS
```

As hinted in the code above, it would be nice if there was a way to have the mechanism modify a non-standard set of variables (`PI_*` in my example) for the case where that Makefile needs these variables in some cases and not others.

Did I overlook an existing mechanism like this in Autosetup, or is this a good feature to add to Autosetup? I can see lots and lots of use for something like this.

A possible extension to this idea is to implement it in terms of `pkg-config`. To make it work with the above use case, you'd need a way to override `PKG_CONFIG_PATH` before calling `pkg-config --cflags bcm_host` and such because this package doesn't install itself to the default search path for `pkgconfig`. This could just be a higher-level wrapper function on the basic function, taking just the `pkgconfig` package name and optional `PKG_CONFIG_PATH` value and providing all of the parameters to the lower-level version.

**Comment by msteveb** [comment]
I'd like to reuse the pkg-config support for this if possible.
You can test it by doing:

   set ::env(PKG_CONFIG_PATH) <dir>
   pkg-config bcm_host

If we provide a nice syntax for setting $PKG_CONFIG_PATH and then restoring it, will this work?

**Comment by tangentsoft** [comment]
I've taken a look at `autosetup/pkg-config.tcl` and it looks like it's doing a lot of what I already want. I think it just needs to have a sub-feature factored out that lets it accept the flags and such from two sources: either from a given path (e.g. my `/opt/vc` example) or from `pkg-config`. 

My wish for a prefix on the outputs is already provided; it doesn't modify the global CFLAGS and such, which is good for me.

As for the `PKG_CONFIG_PATH`, that sounds like a simple extension to the existing module, which I didn't know about when I wrote the above. I only brought up `pkg-config` as a natural extension to my basic idea.

**Comment by msteveb** [comment]
Great. If you want to submit a patch I'll take a look at it

**Comment by tangentsoft** [comment]
I got stuck trying to figure out your custom module system, which is currently [undocumented](http://msteveb.github.io/autosetup/developer/modules/).

(Incidentally, is there a way to contribute to the docs? There's a lot more about Autosetup than just this that's undocumented short of [RTFS](http://catb.org/jargon/html/R/RTFS.html). Given how few people speak Tcl fluently these days, I think the docs should rely a lot more heavily on pre-tested recipes than on the user's knowledge of Tcl. In that way, use of this project could spread outside the narrow world of those fluent in Tcl.)

I wanted to add a `--path` option to the module to let the user extend or override `PKG_CONFIG_PATH` without modifying `::env` directly but I don't see how you actually pass that option.

I think my patch will work as-is, but without a way to test it, I'm stuck:

```tcl
--- /var/folders/09/flxc8yw51_33gv806w5txm4m0000gn/T//pkg-config~orig.tcl 2019-08-09 03:29:30.000000000 -0600
+++ /usr/local/src/pidp8i/trunk/autosetup/pkg-config.tcl  2019-08-09 03:19:18.000000000 -0600
@@ -11,12 +11,17 @@
 # If the C compiler doesn't support '-print-sysroot', the path can be supplied
 # by the '--sysroot' option or by defining 'SYSROOT'.
 #
+# The --path module option can be used to extend (or set) the
+# PKG_CONFIG_PATH envrionment variable used by pkg-config to find
+# its *.pc files.
+#
 # 'PKG_CONFIG' may be set to use an alternative to 'pkg-config'.
 
 use cc
 
 module-options {
   sysroot:dir => "Override compiler sysroot for pkg-config search path"
+    path:dir    => "Set PKG_CONFIG_PATH before calling pkg-config"
 }
 
 # @pkg-config-init ?required?
@@ -38,6 +43,14 @@
   define PKG_CONFIG [get-env PKG_CONFIG pkg-config]
   msg-checking "Checking for pkg-config..."
 
+    if {[opt-str path o]} {
+        if {[string length ::env(PKG_CONFIG_PATH)]} {
+            set ::env(PKG_CONFIG_PATH) "$::env(PKG_CONFIG_PATH):$o"
+        } else {
+            set ::env(PKG_CONFIG_PATH) $o
+        }
+    }
+
   if {[catch {exec [get-define PKG_CONFIG] --version} version]} {
       msg-result "[get-define PKG_CONFIG] (not found)"
       if {$required} {
```

As for refactoring `pkg-config.tcl` to give a lower-level mechanism that lets you do things like in my original issue posting without involving `pkg-config`, I've since found that `bcm_host` on a Raspberry Pi *does* have a `pkg-config` definition, so I don't actually need the feature any more. With this `--path` patch in place (or direct `::env` hackery if you reject the patch) I can get by with what's already provided, so I've lost motivation to refactor `pkg-config.tcl` in the proposed way.

**Comment by msteveb** [comment]
Fair enough, re documentation. Never enough time. I'll see if I can find some time. Including making it easy for others to contribute.

In the meantime, how about this (can't use something so generic as --path):

```
diff --git a/lib/pkg-config.tcl b/lib/pkg-config.tcl
index 0883e4c..e634755 100644
--- a/lib/pkg-config.tcl
+++ b/lib/pkg-config.tcl
@@ -17,6 +17,7 @@ use cc
 
 module-options {
 	sysroot:dir => "Override compiler sysroot for pkg-config search path"
+	pkg-path:dir => "Add the given path to \$PKG_CONFIG_PATH, may be given multiple times"
 }
 
 # @pkg-config-init ?required?
@@ -108,7 +109,21 @@ proc pkg-config {module args} {
 		return 0
 	}
 
-	if {[catch {exec [get-define PKG_CONFIG] --modversion "$module $args"} version]} {
+	# If pkg-path is given, append those paths to $PKG_CONFIG_PATH temporarily
+	set save_pkg_path [getenv PKG_CONFIG_PATH ""]
+	set pkg_paths [opt-val pkg-path]
+	if {[llength $pkg_paths]} {
+		if {$save_pkg_path ne ""} {
+			set new_pkg_path $save_pkg_path$::tcl_platform(pathSeparator)
+		} else {
+			set new_pkg_path {}
+		}
+		append new_pkg_path [join $pkg_paths $::tcl_platform(pathSeparator)]
+		set ::env(PKG_CONFIG_PATH) $new_pkg_path
+	}
+	set rc [catch {exec [get-define PKG_CONFIG] --modversion "$module $args"} version]
+	set ::env(PKG_CONFIG_PATH) $save_pkg_path
+	if {$rc} {
 		msg-result "not found"
 		configlog "pkg-config --modversion $module $args: $version"
 		return 0
```

**Comment by tangentsoft** [comment]
Regarding time, that's why I said "contribute." I may be in a better position to write some of it than you simply because I'm coming at it from a naive perspective, so I can explain concepts from the perspective of an outsider to the project.

Might I suggest using [Fossil](https://fossil-scm.org/) for the docs with [an automatic mirror of that repo up to GitHub](https://fossil-scm.org/fossil/doc/trunk/www/mirrortogithub.md)?

If you want to see the quality of my documentation work, here's [a timeline of my recent contributions to Fossil](https://fossil-scm.org/fossil/timeline?u=wyoung&c=2019-08-09+12%3A15%3A02&y=a), which is mostly documentation work.

As for your patch, I'm still missing a key bit of info: how do I pass this new `--pkg-path` parameter into the module?

As for its name, my weak Tcl-fu does reveal that you're reusing the global option table for module options, but I thought module options were prefixed by the module name, effectively namespacing them. And if not, then why not? :)

**Comment by msteveb** [comment]
[We will talk about the docs separately]

I think your misunderstanding is that **module-options** are global options, the same as **options** in auto.def, as you have discovered. Why not namespace them? Because modules such as **cc** and **system** want to be able to support autoconf-compatible options such as **prefix**. You can easily add a module prefix if appropriate (hence **--pkg-path**)

**Comment by msteveb** [comment]
Take a look here for contributing to the documentation: https://github.com/msteveb/autosetup-docs

**Comment by msteveb** [comment]
I'm closing this ticket. I think what we have for pkg-config is working well. Open a new ticket if there is something specific that is still needed.
