### ISSUE TITLE
CXX is being set to "false"

### ISSUE THREAD

**Issue by sgbeal** [msteveb/autosetup#53]
Autosetup version: 732d2b367db pulled a few hours ago.

i'm not 100% certain this is a bug, but it's bitten me twice now and certainly seems like one:

i'm on a system with no `c++` installed. My `auto.def` is implicitly checking for C++ via:

```
cc-with {-lang c++} { ... }
```

And the end result is that CXX gets set to "false" (without the quotes). That, of course, causes make to try to use `false` as the C++ compiler.

i've worked around this by doing:

```
set cxxCheck [get-define CXX]
if {false eq $cxxCheck} {
  define CXX ""
}
```

But that seems really kludgy.

Can you confirm whether "false" is the expected value for a binary which is not found?

**Comment by msteveb** [comment]
It is intentional, as explained here:

```
# XXX: Could avoid looking for a C++ compiler until requested
# Note that if CXX isn't found, we just set it to "false". It might not be needed.
if {[env-is-set CXX]} {
    define CXX [find-an-executable -required [get-env CXX ""]]
} else {
    define CXX [find-an-executable [get-define cross]c++ [get-define cross]g++ false]
}
```

If you don't have a C++ compiler, why do you care what CXX is set to? Can you offer a suggestion for better behaviour?

**Comment by sgbeal** [comment]
That's the thing: my makefiles care whether there's a C++ compiler, but don't *require* it. Optional C++ bits get built if it's there.

My suggestion would be to define CXX to the path to the compiler, i.e., the empty string:

```
CXX := @CXX@
...
ifneq (,$(CXX))
...
endif
```

What currently happens is that the compiler is effectively set to the wrong executable: `/bin/false` (without the leading path part).

**Comment by msteveb** [comment]
So we can just remove the "false" from the end of that check.
I don't mind that.

**Comment by sgbeal** [comment]
:-D. i think that's the right thing to do, for consistency's sake.

**Comment by msteveb** [comment]
Done
