### ISSUE TITLE
Question about user option declarations in auto.def

### ISSUE THREAD

**Issue by pdietl** [msteveb/autosetup#54]
In the documentation, the user options section syntax is described as follows:
```
options {
    boolopt            => "a boolean option which defaults to disabled"
    boolopt2=1         => "a boolean option which defaults to enabled"
    stringopt:         => "an option which takes an argument, e.g. --stringopt=value"
    stringopt2:=value  => "an option where the argument is optional and defaults to 'value'"
    optalias booltopt3 => "a boolean with a hidden alias. --optalias is not shown in --help"
    boolopt4 => {
        Multi-line description for this option
        which is carefully formatted.
    }
}
```
# Question 1

However, examining the function `options-add` https://github.com/msteveb/autosetup/blob/732d2b367dbc28b2ab6902bcd6dd51b49df7287b/autosetup#L384-L393

...etc

let's checkout this area: https://github.com/msteveb/autosetup/blob/732d2b367dbc28b2ab6902bcd6dd51b49df7287b/autosetup#L457-L489

This is the case in which a line in the `user options` section does contain a colon, and thus the option is a string option.
Looking at line https://github.com/msteveb/autosetup/blob/732d2b367dbc28b2ab6902bcd6dd51b49df7287b/autosetup#L462 you see a comment which implies to me a user options config line that may look like this: 
`with-option-foo:name=default`

However, I see no mention of this in the documentation. Is this an undocumented feature?

I also find it non-intuitive that using the `with-option-foo:name=default` syntax will result in the _help text_ describing the argument to `--with-option-foo=` as `name`, but will internally create a variable that holds the value of the argument as 
`with-option-foo`.
My expectation is that that syntax would result in the help for the argument being `?=y?` and the internal variable being declared as `name` with the value of `default` or whatever the user passes.
# Question 2
Similar to my previous question, it seems that this area of that function:
https://github.com/msteveb/autosetup/blob/732d2b367dbc28b2ab6902bcd6dd51b49df7287b/autosetup#L482-L488

is the implementation of this part of the documented syntax for user options:
`tringopt2:=value  => "an option where the argument is optional and defaults to 'value'"`

This sets what the default value looks like in the help text, but does not actually propagate this value into `autosetup(optdefault)`, as I think the documentation implies.

Further, this line https://github.com/msteveb/autosetup/blob/732d2b367dbc28b2ab6902bcd6dd51b49df7287b/autosetup#L479
sets `defaultvalue` in the case of a `:`, but we never add this default value to `autosetup(optdefault)`

Is this also a mistake?

**Comment by msteveb** [comment]
Regarding question (1), I think this is just a holdover from an earlier way of doing things. There are only two supported string options syntaxes, option=value and option:=value, as explained in the documentation.

I'll remove the checking for option:name=value

**Comment by msteveb** [comment]
Regarding (2), this default doesn't set the default value of the option as such. It gives a value in case the option is provided but without an option. For example:

``install:=/usr/local``

Allows us to then run:

``./configure --install``

in which case it will install to /usr/local, or

``./configure --install=/usr``

in which case it will install to /usr. This is a bit different from options-defaults (and autosetup(optdefault)) where the option is considered to be set, even if not explicitly given by the user. I think the above opt:name=default syntax was attempting to do something similar, but better to just use options-defaults I think.

**Comment by pdietl** [comment]
> in which case it will install to /usr. This is a bit different from options-defaults (and autosetup(optdefault)) where the option is considered to be set, even if not explicitly given by the user. I think the above opt:name=default syntax was attempting to do something similar, but better to just use options-defaults I think.

Oh I see that is quite reasonable. Thanks for explaining. Do you think I/you could add a little more detail to the documentation? :)

**Comment by pdietl** [comment]
The whole reason that I got into this area of the code is because I'm trying to add an option to Fossil for bash completions.

What I want to do is default to indeed installing bash completions, but the user can specify something like `--with-bash-completions-dir` equal to `n` or `no` to disable it, or equal to `<some path>`.

Any advice on how to accomplish this and make the intention clear in the help text of `./configure`?

**Comment by msteveb** [comment]
Sure, I'll think about how to update the documentation. Why do you want n or no? Surely if they just don't specify anything, that will disable it, right?.

**Comment by msteveb** [comment]
Otherwise:

``with-bash-completions-dir:path => "Directory for bash completions, or 'none' to disable"``

```
if {[opt-str with-bash-completions-dir o]} {
    if {$o ni {none n no}} {
        puts "Setting bash completions dir to $o"
    }
}
```

**Comment by msteveb** [comment]
BTW, autosetup(optdefault) is only used to replace @default@ in the help text.

**Comment by msteveb** [comment]
Actually, now I look into it further, there is more to it. I will go through it carefully and update the docs to match reality.

**Comment by pdietl** [comment]
Ok That is a good suggestion. By the way, I really love this project so much more than autoconf. autoconf is impossible to reason about.

In the case that the user does not pass the bash completions flag, I want to
1. try to find the directory via pkg-config
2. use a hard-coded default location based on datadir.

To accomplish 1, I want to make a PR to expand the `pkg-cfg` module to allow for retrieving arbitrary variables about a module. Does that sound ok?

**Comment by msteveb** [comment]
Fair enough. Agree, autoconf is ... painful. Sure, PRs are welcome.

**Comment by sgbeal** [comment]
Autoconf: an old online colleague of mine renamed that whole toolset to the *GNU "Auto, my ass!" Tools*.

**Comment by msteveb** [comment]
I've pushed an update that documents the "string option with default" case and handles it properly. Thanks for the report.
