### ISSUE TITLE
Testing 

### ISSUE THREAD

**Issue by pdietl** [msteveb/autosetup#55]
I see that `make test` runs the tests in the `testsuite` directory, but there are some files that look like tests in the `examples/testbed` directory. Are those officially considered part of testing or not?

Specifically, I am looking to add tests for a new pkg-config-related function, but I don't know where to put it. The only other testing of pkg-config is in the `examples/testbed` directory.

**Comment by msteveb** [comment]
Ideally all tests would be added to the automated tests in the testsuite directory. But some tests are hard to automated, so examples/testbed is for ad-hoc testing. So tests can be added there if too hard to automate.
