### ISSUE TITLE
autosetup-find-tclsh not finding jimsh0

### ISSUE THREAD

**Issue by sgbeal** [msteveb/autosetup#59]
Using the current trunk, as of yesterday:

```
$ ./autosetup/autosetup-find-tclsh 
/usr/bin/tclsh

# But jimsh0 is here:

$ l autosetup/jimsh0
-rwxrwxr-x 1 stephan stephan 314656 Oct 15  2018 autosetup/jimsh0
```

But using 0.6.9 it works as expected:

```
$ ./autosetup/autosetup-find-tclsh 
/home/stephan/fossil/libfossil/autosetup/jimsh0
```

i haven't looked into what the exact problem is, though.

**Comment by msteveb** [comment]
See 0e47e825702ed62ae687bbf52d3777753be2bea6
Now jimsh0 is built (and expected) in the current directory (the build directory) rather than the source directory.
