### ISSUE TITLE
Conditional inclusion doesn't work

### ISSUE THREAD

**Issue by gahr** [msteveb/autosetup#64]
Is this supposed to work in a Makefile template?

```
@if INCLUDE_IT
"INCLUSION ENABLED"
@include sub.make
@else
"INCLUSION DISABLED"
@endif
```

I thought it was, and we're relying on it some.. but apparently it doesn't. The test I put in place over [here](https://github.com/gahr/autosetup/commit/ce076b83adcac0124cc3d6c22a2c8f77b841c55c) generates the following Makefile

```
# I have been included
"INCLUSION DISABLED"
```

So the conditional block works somehow, i.e., I don't get the "INCLUSION ENABLED" string in the Makefile, but apparently the `@include` directive doesn't care?

**Comment by msteveb** [comment]
Thanks. I changed the fix slightly and brought the tests into the automated test suite.

**Comment by gahr** [comment]
Ah yeah - I like your version better too, thanks!
