### ISSUE TITLE
make-template's UPPERCASE rule vs leading underscores

### ISSUE THREAD

**Issue by sgbeal** [msteveb/autosetup#68]
From the make-template docs:

```
# Where 'NAME' is a defined variable name and '@else' is optional.
# Note that variables names *must* start with an uppercase letter.
...
# In the general Tcl expression, any words beginning with an uppercase letter
# are translated into [get-define NAME]
```

While working on porting a large, age-old build to autosetup i've come across two vars which _should_ work with `@if FOO` but cannot because they start with an underscore: `_FILE_OFFSET_BITS` and `_LARGE_FILES`.

My thinking, perhaps naive, is that it should be possible to do something like:

```
@if _FILE_OFFSET_BITS
...
@endif
```

but that won't work. `include-file` has this snippet:

```
# Translate alphanumeric ABC into [get-define ABC] and leave the
# rest of the expression untouched
regsub -all {([A-Z][[:alnum:]_]*)} $condargs {[get-define \1]} condexpr
```

and i'm wondering whether that regsub should start with `_*[A-Z]...` or `_{1,2}[A-Z]...`.

Am i overthinking this? Is this an imaginary problem?

**Comment by msteveb** [comment]
That may be reasonable, but I'd probably suggest just setting another variable if necessary instead.

`define HAVE_FILE_OFFSET_BITS [is-defined _FILE_OFFSET_BITS]`

But probably even simpler is just to add to cflags if necessary:

```
if {[is-defined _FILE_OFFSET_BITS]} {
  define-append AS_CFLAGS -D_FILE_OFFSET_BITS=[get-define _FILE_OFFSET_BITS]
}
```

Or even better, just generate a config.h with make-config-header and then it will be defined if necessary

**Comment by sgbeal** [comment]
> But probably even simpler is just to add to cflags if necessary:

Fair point. That's a perfectly reasonable approach.

> Or even better, just generate a config.h with make-config-header and then it will be defined if necessary

That was my initial try but it visually differs so much from the one the SQLite project currently has that i hand-wrote one which looks more similar. Whether or not the appearances really matter in that case remain to be seen - this may well be yet another case of over-engineering on my part. i'll need to try it again with make-config-header now that i can actually build most of the project with autosetup.

Semi-related: as of mere moments ago, my experimental branch of the sqlite3 project builds all of its TCL-generated code using the autosetup-provided copy of jimsh :).
