### ISSUE TITLE
--help broken on QNX by call to stty

### ISSUE THREAD

**Issue by sgbeal** [msteveb/autosetup#69]
This is forwarded from a colleague who is using QNX but has no github account. He writes:

---------

FYI.. about the `./configure --help` flag that doesn't works... it seems to be because because autosetup try to call stty size.... 

it fail with:

> **`./autosetup/autosetup:571: Error: expected integer but got "Invalid"`**  

when it try to decrement cols. it expect "cols" to be an integer while on QNX, if I run **`stty size`**, I get.

```
$ stty size
stty: Invalid argument 'size'
```

---------

If there's any more info he can provide which might help, just let me know, with the caveat that the turnaround on such details may be a day or two.

**Comment by msteveb** [comment]
Thanks for the report. I pushed a fix.
