### ISSUE TITLE
Question: expectations for %s placeholder in defined vars?

### ISSUE THREAD

**Issue by sgbeal** [msteveb/autosetup#70]
Some `define`'d vars have a `%s` in them as a placeholder for a or a version number, e.g.:

```
#define SH_LINKRPATH "-Wl,-rpath -Wl,%s"
#define SH_SOEXTVER ".so.%s"
```

My question is: is it expected that the client should replace those `%s` bits with the appropriate info, or is there some voodoo elsewhere which can/does do so?

**Comment by msteveb** [comment]
Yes, the expectation is that your build system (e.g. Makefile) will replace those as necessary.

So for SH_SOEXTVER, %s should be replaced with the default shared library version.
For SH_LINKRPATH, %s should be replaced with the path (if you need to set an rpath)

Is that clear?

For example, with the tmake build system:

`SharedLib --publish --install=/lib --version=1.2.3 fdcallback fdcallback.c`

Translates into:

`cc  -shared  -o objdir/fdcallback/libfdcallback.so.1.2.3 -Wl,-soname,libfdcallback.so.1 objdir/fdcallback/fdcallback.o -Lobjdir/.publish/lib -ltimer
`

So you can see that the filename is libfdcallback.so.1.2.3, but the soname is libfdcallback.so.1 (and appropriate symlinks are created).

In your build system you need to figure out how to determine that soname, the define is to make it easy to use cross-platform

**Comment by sgbeal** [comment]
Great, thank you. That was my assumption but didn't want to step in a pothole if that weren't the case.
