### ISSUE TITLE
ANN: autosetup/jam

### ISSUE THREAD

**Issue by alex-shpilkin** [msteveb/autosetup#8]
(Written here for the lack of a mailing list for autosetup.)

It may be some 10 years too late to use Jam (or, more specifically, the FreeType.org version of it, FT-Jam)  as a build tool, but I still find it nice; and its build scripts are concise and to the point. So, here is a plugin for autosetup that provides the glue between an autosetup-driven configuration system and a Jam-driven build. It works for C projects on Linux at least and supports out-of-tree builds, cross-compilation (at least I've succeeded in doing a MinGW cross-compile on Linux) and shared libraries with versioned SONAMEs. Unfortunately, no automake-compliant `jam (un)install` targets yet, and much more testing on different platforms is needed.

Available in Git: http://github.com/alex-shpilkin/autosetup-jam. A port of the `typical` autosetup example is included. (I'm not experienced in automake, so no Makefile.am ports yet.)

The question is whether the adopted 'plugin' strategy is really adequate. It means copying the plugin files over to the autosetup _development_ directory; it also involves extending autosetup functionality that wasn't really meant to be. In particular, I had to provide a `local.tcl` file in order to customize `--install` and `--init` stages, and the latter involved copying a considerable chunk of code from `init.tcl` (the part that creates a `configure` script).

**Comment by msteveb** [comment]
I'm closing this ticket. I think the plugin mechanism for autosetup works well enough.
